- type: playTimeTracker
  id: JobVagabond

- type: playTimeTracker
  id: JobNanoTrasenOffical

- type: playTimeTracker
  id: JobBlueShield

- type: playTimeTracker
  id: JobNanoTrasenEmployee

- type: playTimeTracker
  id: JobAdvisor

- type: playTimeTracker
  id: JobBaron

- type: playTimeTracker
  id: JobGuard

- type: playTimeTracker
  id: JobGuardCaptain

- type: playTimeTracker
  id: Beggar

- type: playTimeTracker
  id: Farmer

- type: playTimeTracker
  id: Physician

- type: playTimeTracker
  id: JobSalvager

- type: playTimeTracker
  id: JobTavernKeeper

- type: playTimeTracker
  id: JobTechnician

- type: playTimeTracker
  id: JobDARKSTARChaplain